SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    CUSTOMER_CITY,
    PRODUCT_CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT_PCT,
    PAYMENT_METHOD,
    ORDER_STATUS,
    SOURCE_FILE_NAME,
    INGESTION_TIMESTAMP
FROM {{ source('bronze', 'clean_sales') }}