USE WAREHOUSE SALES_WH;
USE DATABASE SALES_DW;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '<YOUR_AWS_ROLE_ARN>'
STORAGE_ALLOWED_LOCATIONS = (
    's3://<S3_BUCKET_NAME>/sales/raw/'
);