USE WAREHOUSE SALES_WH;
USE DATABASE SALES_DW;
USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE SALES_STAGE
    STORAGE_INTEGRATION = S3_INT
    URL = 's3://<S3_BUCKET_NAME>/sales/raw/'
    FILE_FORMAT = CSV_FORMAT;