{{ config(
    materialized='table'
) }}

SELECT

    COUNT(*) AS TOTAL_ORDERS,

    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,

    SUM(QUANTITY) AS TOTAL_QUANTITY,

    ROUND(SUM(NET_AMOUNT),2) AS TOTAL_REVENUE,

    ROUND(AVG(NET_AMOUNT),2) AS AVG_ORDER_VALUE,

    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,

    MAX(ORDER_DATE) AS LAST_ORDER_DATE

FROM {{ ref('silver_sales') }}