{{ config(
    materialized='table'
) }}

SELECT

    PRODUCT_CATEGORY,

    COUNT(*) AS TOTAL_ORDERS,

    SUM(QUANTITY) AS TOTAL_QUANTITY,

    ROUND(SUM(NET_AMOUNT),2) AS TOTAL_REVENUE,

    ROUND(AVG(NET_AMOUNT),2) AS AVG_ORDER_VALUE

FROM {{ ref('silver_sales') }}

GROUP BY PRODUCT_CATEGORY

ORDER BY TOTAL_REVENUE DESC